---
name: Tag

on:
  push:
    branches:
      - main
      - SRA-167


jobs:
  ## tag
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set GIT_TAG
        run: |
          export GIT_TAG=$(cat .version | tr -d " \t\n\r")

      - name: git-tag
        uses: pkgdeps/git-tag-action@v2.0.1
        with:
          version: ${{ env.GIT_TAG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: ""
