---
name: Tag

on:
  push:
    branches:
      - main


jobs:
  ## tag
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set GIT_TAG
        run: |
          export GIT_TAG=$(cat .version | tr -d " \t\n\r")

      - name: git-tag
        uses: pkgdeps/git-tag-action@v2.0.1
        with:
          version: $GIT_TAG
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: sourcefuse/terraform-aws-cloud-custodian
          # git_commit_sha: # optional
          # git_tag_prefix: # optional, default is ''
